In [1]:
import sys
import os

# プロジェクトルートを Python パスに追加
project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

In [2]:
import numpy as np
from graph.prior import GaussianPrior
from graph.measurement import GaussianMeasurement
from core.uncertain_array import UncertainArray as UA

In [5]:
# 1. Prior → X
X = GaussianPrior(shape=(4, 4), mean=0, var=1.0, seed=42)

# 2. X → Measurement（観測値 y）
obs_data = np.ones((4, 4), dtype=np.complex128)
meas = GaussianMeasurement(X, obs_data, var=0.25)

# 3. メッセージ伝播
X.parent.forward()   # Prior → X
X.forward()          # X → Measurement
meas.backward()      # Measurement → X
X.compute_belief()   # Belief 更新

# 4. 結果確認
print("Mean:\n", X.belief.data)
print("Precision:\n", X.belief.precision)

Mean:
 [[0.8430935 +0.05214924j 0.65292404-0.13560648j 0.90612983+0.12423163j
  0.93301594-0.00706059j]
 [0.52408196-0.02614349j 0.61584401-0.09629798j 0.81807936+0.17289345j
  0.75527654-0.02185377j]
 [0.79762396-0.0605747j  0.67936137-0.0497992j  0.92436565+0.07527989j
  0.90999639+0.0516816j ]
 [0.80933815+0.05836921j 0.95941598+0.06092729j 0.86611581+0.30287471j
  0.67847769-0.05747576j]]
Precision:
 [[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]
